### ISSUE TITLE
Unable to run jam-cli in docker

### ISSUE THREAD

**Issue by drkstr101** [paketo-buildpacks/packit#104]
## What happened?

Greetings all,

I was super stoked when I found out I no longer have to write buildpack API in bash! I'm running into a bit of trouble  using `jam` cli, specifically, the one installed from `tools.sh` via `scripts/package.sh`. This may not be specific to packit, and could just be an issue with the scrips themselves, although I did get the same results with the manually downloaded version from Releases.

Am I perhaps missing something I need in the Dockerfile?

```Dockerfile
FROM docker:latest

# Install build deps
RUN apk add --no-cache --update bash \
    ca-certificates \
    curl \
    git \
    git-lfs \
    gnupg \
    gzip \
    openssl \
    wget && update-ca-certificates

# Install go
COPY --from=golang:1.14-alpine /usr/local/go/ /usr/local/go/
ENV PATH="/usr/local/go/bin:${PATH}"

#Install Pack
ARG pack_version=0.15.1
RUN wget -q https://github.com/buildpacks/pack/releases/download/v${pack_version}/pack-v${pack_version}-linux.tgz && \
    tar -zxf pack-v${pack_version}-linux.tgz && \
    mv pack /usr/local/bin/pack && \
    rm pack-v${pack_version}-linux.tgz

VOLUME /app
WORKDIR /app
ADD ./node-engine .

ENTRYPOINT []
CMD [ "bash", "--" ]
```

Example launch.sh:

```shell
#!/usr/bin/env bash

set -eu
set -o pipefail

if [[ ! -d "./node-engine" ]]; then
    # Chosen at random from recently updated
    git clone https://github.com/paketo-buildpacks/node-engine
fi

docker build . --tag my-app
docker run -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$(pwd)/node-engine":/app:rw \
    -it my-app /app/scripts/package.sh --version 1.0.0 || echo "failed"

ls ./node-engine/.bin -lR
```

Please provide some details about the task you are trying to accomplish and
what went wrong.

```
...
Successfully tagged my-app:latest

Preparing repo...

Packaging buildpack into /app/build/buildpack.tgz...

Installing jam v0.4.2
/app/scripts/package.sh: line 95: /app/.bin/jam: No such file or directory
failed
./node-engine/.bin:
total 11604
-rwxr-xr-x 1 root root 11878843 Jan  4 06:55 jam
```

note: __/app/scripts/package.sh: line 95: /app/.bin/jam: No such file or directory__

It works as expected on the host system.

* What were you attempting to do?

Hello, World! (Paketo Buildpack)

## Checklist

Please confirm the following:

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

Cheers, and thank you for your time!!

~Aaron

**Comment by sophiewigmore** [comment]
Hi @drkstr101, glad to see packit has been helpful! When you look inside the `/app/.bin` directory, do you see the `jam` executable? If so, are you able to manually execute `/app/.bin/jam`? 
Also, just to clarify, you also saw this error when you manually downloaded a `jam` executable and put it inside `/app/.bin`?

**Comment by sophiewigmore** [comment]
Update, I reproduced this error with your set up and I see the issue you're having. When I manually curl the `jam` executable and `chmod` it, it still gives the error "No such file or directory" that you are seeing. It might be an issue with the linux runtime you are specifying in the Dockerfile?

**Comment by drkstr101** [comment]
Thanks, this gives me somewhere to start digging. I will start from full and see when I end up triggering it.

And to answer your question, it's kind of hard to tell. The file is there and shows up in manifest. But I cant stat or cat or get any real handle on it, but I didn't dig too far into it because I wasn't even sure what it was at the time. I ended up just calling `pack` for the ci build, but it has now piqued my curiosity.

**Comment by drkstr101** [comment]
Hey, I think my code may have failed review there!


if [[ ! -d "./node-engine" ]]; then
    # Chosen at random from recently updated
    git clone https://github.com/paketo-buildpacks/node-engine
fi
# shouldn't I be in node-engine dir  at this point? Did I miss it?
docker build . --tag my-app

**Comment by drkstr101** [comment]
/app/scripts/package.sh: line 95: **/app/.bin/jam**: No such file or directory
failed
**./node-engine/.bin**:

Issue identified. you can tag this one `PEBKAC`!  :)

**Comment by drkstr101** [comment]
@sophiewigmore 

PS: sometime soon here I was going to take a stab at a `vertx-native-image` buildpack. If you wish to adopt it I will just contribute any updates there.

I am just now able to build the damned thing, so next step is to solidify an API.

Is there some kind of official process to propose newly supported APIs?

**Comment by sophiewigmore** [comment]
@drkstr101 Hey, awesome that you figured out the issue! Although, I'm not sure that I completely follow what the solution was. Could you explain in a little bit more detail?

In terms of the `vertx-native-image` buildpack, that's great! If you have questions or want feedback, feel free to join [Paketo slack](https://join.slack.com/t/paketobuildpacks/shared_invite/zt-ded61bqr-Rw_uK3u6MvaeLPhxEIBcLg) and drop a line. Our [contribution guide](https://github.com/paketo-buildpacks/.github/blob/main/CONTRIBUTING.md) should have a lot of useful information, but of course feel free to reach out if you have more questions, or drop into our weekly [working group meeting](https://github.com/paketo-buildpacks/community#working-group-meetings)

**Comment by ryanmoran** [comment]
You can also start a more general conversation about it or other topics in our feedback discussion forum: https://github.com/paketo-buildpacks/feedback/discussions.

**Comment by drkstr101** [comment]
I should probably double check my assumptions , bu it seems as if it is trying to access the binary at two seperate locations, causing the incorrect one to exit early on a mundane, yet misleading, bash syntax error.

To make things worse, I made the same mistake twice. Both in my original code, and with the test case I whipped up from scratch.

Should it be `/app/node-engine/.bin/jam` or  `/app/.bin/jam`. I see it trying to access both in posted console output.

**Comment by drkstr101** [comment]
PS: didn't meen to just skip over all the rest of of your comment. I am looking forward to it! I am sure I will need a bit of guidance here and there, but I think it will be a great experience for me to design and advocate for my own RPC. I can see firsthand why stable APIs would be strongly desired in this space.

Cheers, and thank you for making me feel so welcome!
