### ISSUE TITLE
Self-nomination as tooling contributor

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/packit#117]
In keeping with [the Paketo Buildpacks Governance document](https://github.com/paketo-buildpacks/community/blob/main/GOVERNANCE.md), I am self-nominating as a contributor to the Tooling subteam.

I have recently contributed:
- work on the `Serve()` matcher in occam: https://github.com/paketo-buildpacks/occam/pull/75
- changing `fs.Sum()` to accept variadic args: https://github.com/paketo-buildpacks/packit/pull/90
- builders' shared workflows to github-config: https://github.com/paketo-buildpacks/github-config/pull/228
-  commit signing capability to the create-commit action: https://github.com/paketo-buildpacks/github-config/pull/229
- actions checking for human commits and unverified commits on PRs: https://github.com/paketo-buildpacks/github-config/pull/219

**Comment by ryanmoran** [comment]
Approved! @fg-j you should now have Contributor status across all of the Tooling repos in the `paketo-buildpacks` and `paketo-community` organizations.
