### ISSUE TITLE
jam update-buildpack fails with permissions issue on private GCR registry

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/packit#175]
## What happened?

* What were you attempting to do?
```
jam update-buildpack --buildpack-file buildpack.toml --package-file package.toml
```
With a `buildpack.toml` and `package.toml` that contain references to images in a private GCR registry.

* What did you expect to happen?

I expected the command to inherit my docker auth credentials and successfully update the buildpack files.

* What was the actual behavior? Please provide log output, if possible.

```
Error: failed to get buildpackage ID for gcr.io/tanzu-buildpacks/cpython:0.1.0: GET https://gcr.io/v2/tanzu-buildpacks/cpython/manifests/0.1.0: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials.
```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
`jam v0.11.0`

* What buildpacks are you using? Please include versions.
N/A

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
N/A

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
This [`buildpack.toml`](https://github.com/pivotal-cf/tanzu-python/blob/d139f10676d90c9c1d4099e0ef048700b2f01f78/buildpack.toml)

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by ryanmoran** [comment]
Did you authenticate with the registry first? I believe you would need to do a `docker login` with credentials that work for that registry. After that, it should use the keychain from the Docker daemon.

**Comment by fg-j** [comment]
We did authenticate with the registry first (`echo $GCR_ACCOUNT_KEY_JSON | docker login -u _json_key --password-stdin https://gcr.io`).

It's worth noting that while logged in with the same credentials, `docker pull gcr.io/tanzu-buildpacks/cpython:0.1.0` succeeds with no issue, and that the service account used has push permissions on the registry as well.
