### ISSUE TITLE
cargo ConfigMetadataDependency does not represent all Paketo buildpacks' dependency metadata

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/packit#222]
In cargo, there is a `ConfigMetadataDependency` struct that represents the various metadata that can be found in a `[[metadata.dependencies]]` entry in a `buildpack.toml`. This struct includes a [`Licenses` field](https://github.com/paketo-buildpacks/packit/blob/f0fe48c78c285c5ad3879dcbe31c5d98358ece6e/cargo/config.go#L54) that is a slice of strings. This matches the structure of buildpack dependency metadata like what shows up in [the node-engine buildpack](https://github.com/paketo-buildpacks/node-engine/blob/aeb0486f7362ba1af321c9c42a043d45974a639e/buildpack.toml#L18).

However, in buildpacks like the Bellsoft Liberica buildpack, the dependency licenses are represented as an [array of TOML objects with type and URI fields](https://github.com/paketo-buildpacks/bellsoft-liberica/blob/824710855e92ae9fea90ccc4d57afb675184640b/buildpack.toml#L87).

The result is that cargo cannot decode the `buildpack.toml` for buildpacks with dependency licenses represented as TOML objects.

This is just one of a few instances where packit makes assumptions about the structure of the metadata in a `buildpack.toml`. It may be useful to either a) make packit more flexible in how it decodes `buildpack.toml`, and/or b) spec some requirements for packit-compliant buildpack metadata so that buildpack authors can construct `buildpack.toml` that work with packit.

**Comment by sophiewigmore** [comment]
It appears that this issue arose in packit v0.14.1 with the addition of licenses.
