### ISSUE TITLE
Allow `scribe.NewEmitter` to take a `scribe.Logger` without extra wrapping

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/packit#273]
This construction seems kind of awkward. I think we can possibly do better in `scribe` to make it so that this API seems a bit more fluent. Possibly something like this,

```go
logger := scribe.NewEmitter(scribe.NewLogger(os.Stdout).WithLevel(os.Getenv("BP_LOG_LEVEL"))
```

_Originally posted by @ryanmoran in https://github.com/paketo-buildpacks/mri/pull/321#r778349805_

**Comment by sophiewigmore** [comment]
@ryanmoran to me, this is still kind of long. I would almost prefer just deferring all of the logic dealing with the internal Logger to the scribe package, so in the buildpack I could just call:
```
logger := scribe.NewEmitter(os.Stdout).WithLevel(os.Getenv("BP_LOG_LEVEL"))
```

Then, I'd just add an `Emitter.WithLevel` function to scribe. And then theres also no breaking changes. 
What do you think?

**Comment by ryanmoran** [comment]
That works for me.
