### ISSUE TITLE
Make the SBOM Generator an interface instead of a locked down struct

### ISSUE THREAD

**Issue by pringon** [paketo-buildpacks/packit#320]
## What happened?

* What were you attempting to do?

I was trying to modify the SBOMGenerator for the Go buildpack to use the newer version of the syft Cataloger that contains a fix to how components are added.

* What did you expect to happen?

I expected to be able to create a new generator with the correct interface and pass that to `go.Build`.

* What was the actual behavior? Please provide log output, if possible.

The `Generate` method must return a `packit.sbom.SBOM` struct that has a single, private, `syft` field. This makes it impossible to modify outside of the module

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

Pack@v0.24.0

* What buildpacks are you using? Please include versions.

`go-build` paketo buildpack

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
N/A

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
N/A

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by sambhav** [comment]
This has been merged and can be closed?

**Comment by fg-j** [comment]
@pringon Does #327 address your need?

**Comment by pringon** [comment]
Yes it does, thanks! 😄
