### ISSUE TITLE
Implement Buildpack RFC 0100: Replace positional args to buildpack executables with env vars

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/packit#322]
## Blocked
~~This issue is blocked on the release of Buildpack API 0.8.~~

## Summary
Buildpack [RFC0100](https://github.com/buildpacks/rfcs/blob/main/text/0100-buildpack-input-vars.md) replaces positional arguments to build and detect executables with named environment variables as of Buildpack API 0.8 and beyond.

For detection, rather than passing in two [positional arguments](https://github.com/paketo-buildpacks/packit/blob/1c5ad2f17e60d9988d4e9e1518207c54fe8dd66b/detect.go#L89) `<platform>` and `<plan>`, environment variables `CNB_PLATFORM_DIR` and `CNB_BUILD_PLAN_PATH` can be used respectively.

For build, rather than [passing in three positional arguments](https://github.com/paketo-buildpacks/packit/blob/1c5ad2f17e60d9988d4e9e1518207c54fe8dd66b/build.go#L99-L103) for `<layers>`, `<platform>`, and `<plan>` environment variables `CNB_LAYERS_DIR`, `CNB_PLATFORM_DIR`, and `CNB_BP_PLAN_PATH` can be used respectively.

`CNB_PLATFORM_DIR` is the absolute path to the platform directory.
`CNB_BUILD_PLAN_PATH` is the absolute path to the build plan
`CNB_LAYERS_DIR` is the absolute path to the buildpack layers directory
`CNB_BP_PLAN_PATH` is the relevant [Buildpack Plan entries](https://github.com/buildpacks/rfcs/blob/main/text/0100-buildpack-input-vars.md#buildpack-plan-toml) from detection (TOML)

## Proposal
If the buildpack is using Buildpack API 0.8 or higher, the above arguments can be provided with the [same mechanism](https://github.com/paketo-buildpacks/packit/blob/1c5ad2f17e60d9988d4e9e1518207c54fe8dd66b/build.go#L118) used to provide `CNB_BUILDPACK_DIR` in both packit's detec and build. For each of the relevant fields, a `LookupEnv` should be performed to incorporate that value if it is set.

**Comment by fg-j** [comment]
We could consider using https://github.com/Netflix/go-env to unload all the relevant environment variables into a struct 🙂

**Comment by ForestEckhardt** [comment]
I think that I am going to stick with just checking the env var using `os.LookupEnv` I don't think it makes sense to introduce the potential for a parsing error but I am willing to be overruled on this one.
