### ISSUE TITLE
Using CPES in metadata dependencies doesn't parse correctly.

### ISSUE THREAD

**Issue by parigyasingh** [paketo-buildpacks/packit#364]
We are using cpes []{string} instead of cpe string to indicate the metadata dependency in a buildpack that uses packit, 
This is working as intended when we use cpe, but breaks when we try to use cpes (array ).

## Expected Behavior
Ideally both cpe and cpes should work to denote metadata dependencies.

## Current Behavior
cpes - doesn't work as intended.

**Comment by sophiewigmore** [comment]
Hi @parigyasingh which package is breaking within packit?

**Comment by parigyasingh** [comment]
We were trying to hydrate [node-engine](https://github.com/paketo-buildpacks/node-engine) buildpack internally .

**Comment by sophiewigmore** [comment]
@parigyasingh  Are you substituting the `cpe` field for dependencies in the `buildpack.toml`? Can you describe a bit more about your use case? 

It makes sense that you'd see failures with packit because the metadata schema we adhere to is hardened to use just the `cpe` field. We only typically provide one CPE for each dependency, which should in theory be enough to discover information about that dependency. However, I see that the Java buildpacks use `cpes` in their metadata

**Comment by parigyasingh** [comment]
[libpak](https://github.com/paketo-buildpacks/libpak) provides suppport for dependencies using cpes , whereas packit provides only cpe .
It would be ideal if there is consistency between the two, as we are trying to hydrate different buildpacks - some use libpak and other use packit.

**Comment by sophiewigmore** [comment]
@parigyasingh can you help me understand an example of when you'd want multiple CPEs for a dependency?

I'm not against supporting both the `cpe` field and the `cpes` field, but it would be useful to understand why someone would want more than one CPE.

**Comment by sophiewigmore** [comment]
To be clear, I'd be open to a contribution for this fix, but I'd like to understand what the use case is for having more than one CPE as I am not familiar

**Comment by parigyasingh** [comment]
There is no immediate use case of having multiple cpes , but the inconsistency between cpe and cpes in libpak and packit is something we should take care of. We have examples testcases  here in packit repo 
https://github.com/paketo-buildpacks/packit/blob/e3745cd8eb5c40454f8863cf9ea24a7ade62e5c0/sbom/internal/formats/syft2/test-fixtures/snapshot/TestDirectoryEncoder.golden#L18 
particularly for syft where we are using the cpes implementation.
