### ISSUE TITLE
Refactor: extract dependency resolution from postal.Service

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/packit#387]
## Describe the Enhancement

I would like to propose that we extract the [service.Resolve](https://github.com/paketo-buildpacks/packit/blob/56b3d48aa732926df268cdb9470e53cf5193a4a7/postal/service.go#L68-L141) method out of the service object and into a package function. It has no dependencies on the `service` object and it requires no additional injected objects (and hence no mocked dependencies).

This is a pure aesthetic change, and one could argue that there's no functional cost to instantiating a `cargo.Transport` and the `postal.Service` object, but I think it is confusing to do so just to get functionality that does not depend on those objects.

## Motivation

The reason I care about this, is because in https://github.com/paketo-buildpacks/cpython/pull/398 we want to leverage this logic to resolve the dependency versions from buildpack.toml during integration test setup, but we do not need or want to instantiate the [`cargo.NewTransport{}`](https://github.com/paketo-buildpacks/packit/blob/56b3d48aa732926df268cdb9470e53cf5193a4a7/cargo/transport.go#L12) struct which is a required dependency of [`postal.NewService()`](https://github.com/paketo-buildpacks/cpython/pull/398).

**Comment by robdimsdale** [comment]
The priority of this refactor is increasing for me for a couple of reasons:
1. I am seeing opportunities to refactor integration tests to leverage common dependency-management code rather than re-inventing it across multiple tests. See e.g. https://github.com/paketo-buildpacks/cpython/pull/424
1. It will make any feature additions (like #401) easier to implement, test, and consume.

Therefore I will probably take a pass at this soon.

I'd like to get some opinions from @paketo-buildpacks/tooling-maintainers about where this new function should live. Adding it at the package-level won't be a breaking change, as we can preserve the existing `service.Resolve` method (with a deprecation notice), but I'd prefer to pick a package that we all agree on first time.

Currently I'm leaning towards making a new package called `dependency` with just this one package-level function in it. The signature would therefore be `dependency.Resolve()`. I'd rather not make a new object (e.g. `dependency.NewResolver().Resolve()`) but I'm open to that if people feel strongly. It would make it slightly easier to implement interfaces on the consuming side, but only slightly. And a package-level function (where practical) is more idiomatic in Go.

@paketo-buildpacks/tooling-maintainers thoughts?

**Comment by fg-j** [comment]
All in all, I agree that dependency resolution is pretty different from the other stuff that `postal` currently does. (Arguably, `GenerateBillOfMaterials`, too.) I like the idea of it being simpler to call the `Resolve()` function in a variety of scenarios. However, I think `Resolve` is pretty tightly coupled to  [the definition of `postal.Dependency`](https://github.com/paketo-buildpacks/packit/blob/56b3d48aa732926df268cdb9470e53cf5193a4a7/postal/buildpack.go#L12), its return type. Are you also looking to move the definition of `postal.Dependency` into another package? 

To me, it feels odd to have a new package `dependency` with a function `Resolve()` that returns a type that's defined in `postal`.

**Comment by robdimsdale** [comment]
Ah, great catch. I didn't look closely enough at the return type.

I could go either way. I am happy to keep `Resolve()` in the `postal` package, and I could also see the value in moving the dependency definition out to a new `dependency` package.

Yes, it would stutter (`dependency.Dependency`), and yes, it would introduce an inter-package dependency (`postal` depends on `dependency`), but I don't think it's unreasonable to set up this dependency graph.

It seems reasonable to me that a buildpack would want to interact with dependencies separately from downloading them, and so a separate package is justifiable.

However, I really don't object to keeping the `Resolve()` method in postal until we have more feedback on the usage of it.

**Comment by ryanmoran** [comment]
I'd prefer that we avoided making a third `Dependency` type to go alongside those already existing in `postal` and `cargo`. If we did any refactoring, I'd like to see us move dependency resolution into `cargo` since its the package having the most connection to the underlying `buildpack.toml` descriptor file. We could then replace the internal bits in `postal` with the `cargo` implementation and mark the overall `postal.Service.Resolve` method as deprecated.

**Comment by robdimsdale** [comment]
Great call @ryanmoran - I forgot we already had two definitions.

I like the idea of creating `cargo.ResolveDependency()` with the canonical definition of `Dependency` living in the `cargo` package and `postal` leveraging that as appropriate.

I'll take a look at putting a PR together to address this.

**Comment by robdimsdale** [comment]
I'm going to close this as we aren't actively reviewing this potential refactor. The various PRs are also closed, but the code still exists on them if anyone wants to take a look.
