### ISSUE TITLE
How should packit handle dependencies with overlapping stacks?

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/packit#403]
## Background

Currently some buildpacks (e.g. CPython) have multiple dependencies with the same ID and version but with support for different, overlapping, stacks. In this situation, packit is sometimes picking the dependency with support for the `*` stack (i.e. wildcard) instead of the dependency with the more specific (matching) stack dependency.

This causes a problem because there is no requirement that the dependencies behave identically (e.g. in CPython, the dependency with `*` stack support is actually the Python source code and will be compiled dynamically by the buildpack, likely with different flags).

We thought we fixed this specific issue in paketo-buildpacks/python#402 by ordering the `*` stack support lower than any other dependency, but we are still seeing packit selecting the wrong dependency in the CPython buildpack.

To generalize a little, the problem statement is:

**Should packit support dependencies with overlapping stack support?** e.g.:

```
[[metadata.dependencies]]
id = "some-dep"
version = "1.2.3"
stacks = ["stack_a", "stack_b"]

[[metadata.dependencies]]
id = "some-dep"
version = "1.2.3"
stacks = ["stack_b", "stack_c"]
```

## What should packit do?

Essentially I see two options:

1. Make packit more robust to this situation. Deprioritize the `*` stack below specific stacks and (probably) use the order that the dependencies are listed in `buildpack.toml` as a final ordering once all other filtering/version-ordering/stack-ordering has occurred. The buildpack.toml ordering would act as a tie-breaker in the case where multiple dependencies match the current stack.
    * Pro: encapsulates this behavior in packit; does not require buildpack authors to handle anything special in their buildpack execution code
    * Con: It is complex to handle all the edge-cases that could potentially arise.
    * Con: leveraging the buildpack.toml ordering is not particularly intuitive.
1. Do not support multiple dependencies matching the provided stack at all. Instead, require buildpack authors to use different dependency IDs and push the decision of dependency-ID selection to the buildpacks. Once buildpacks have chosen a dependency ID, packit can resolve it as before.
    * Pro: it keeps packit simple
    * Pro: conceptually easier for buildpack authors to understand which dependency will be selected
    * Con: buildpack authors must duplicate some of the logic that could be abstracted within packit to choose a dependency before trying to resolve it via packit. It is possible that we will want to add helper methods to packit to facilitate these questions (e.g. "does the buildpack.toml have a dependency that matches this specific stack?") or change the current packit interface (e.g. do not error when there are no dependencies for a given stack)

**Comment by robdimsdale** [comment]
Just a quick update - it seems that packit is now doing the correct thing. The issue with CPython was a bug in the integration test for the buildpack, not the buildpack itself.

I think that reduces the urgency of this issue to a more academic one, as we currently do not envisage any situation where we have overlapping stacks except the wildcard stack, and that is already handled by paketo-buildpacks/python#402.

**Comment by sophiewigmore** [comment]
I think that overlapping stacks for dependency versions shouldn't be allowed outside of the `*` stack, and for the `*` stack, we should continuing with just deprioritizing it as we have now. I don't see why we should allow for two dependencies with the same version to have overlapping sets of stacks in any other case. It feels unnecessarily complicated

**Comment by ryanmoran** [comment]
I feel that if you have 2 dependencies listed in the metadata with the same version and overlapping stack support, then it should not matter which version is chosen by `packit`. If its required to differentiate between these dependencies, then I'd argue you probably aren't talking about the same thing and you should consider option 2.

As for option 1, I am quite wary of us layering on more semantics to the existing stack ID. It is a very weak way to describe compatibility, especially when its allowed to be set to `*` which means basically nothing is being asserted as to whether this dependency will work.

**Comment by robdimsdale** [comment]
@ryanmoran yeah, that does seem reasonable.

I think it would also be clearer in the buildpack code to differentiate between multiple different types of dependencies (e.g. pre-compiled vs source).

It seems reasonable for the buildpack to ask packit to resolve each set of dependencies separately - the logic would then look something like:
1. resolve "pre-compiled" dependencies for the current stack
1. resolve "source" dependencies for the current stack
1. If there is a pre-compiled dependency, use it.
1. If there is not a pre-compiled dependency, and there is a source dependency, use that (possibly emitting a warning that the build will take a while)
1. If there are no pre-compiled dependencies or source dependencies, fail with error.

I don't think we can force this distinction in packit, though. Even if we required dependencies to follow some common naming scheme (e.g. "[dep]-precompiled", "[dep]-source") - which I think is a bad idea - I'm not convinced it will actually help, because the distinction between pre-compiled and source isn't really something packit can know about in the general case.

I think it would be better to document in packit that we encourage buildpacks to adopt the second option. Perhaps we could also deprecate overlapping stack support in packit, despite the fact we just fixed some bugs to make it work in a repeatable manner.

**Comment by fg-j** [comment]
> I think it would also be clearer in the buildpack code to differentiate between multiple different types of dependencies (e.g. pre-compiled vs source).

This makes sense to me. It also probably simplifies the logic for updating `buildpack.toml` for pre-compiled dependencies and compile-from-source dependencies separately. @paketo-buildpacks/python-maintainers can you comment on how this is working currently in the cpython buildpack?

**Comment by robdimsdale** [comment]
> https://github.com/orgs/paketo-buildpacks/teams/python-maintainers can you comment on how this is working currently in the cpython buildpack?

Yeah, it's not ideal. the Cpython buildpack resolves all dependencies with ID: `python` for the current stack, and determines if it is a source package based on whether the `URI` and `sourceURI` are equal (code [here](https://github.com/paketo-buildpacks/cpython/blob/c306d7ca772b7020bebeff642743e5922e81742a/build.go#L130-L131)). It works, and it's a sufficient discriminator for now but I think it would be better to be more explicit about which dependencies are source vs pre-compiled.

I opened [this issue](https://github.com/paketo-buildpacks/cpython/issues/474) to address this for the various python buildpacks.

**Comment by robdimsdale** [comment]
I think we can close this with the explicit (if slightly weasly) statement that packit's behavior is _undefined_ for dependencies with overlapping stacks as described in the problem statement above.

If something changes and we feel the need to define the behavior, then hopefully we will have some additional context on whether we should support it or fail-fast.
