### ISSUE TITLE
Potential Issue when multiple buildplan entries exist

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/packit#408]
## Expected Behavior

1. Take the pip sample app.
2. Use the paketo-buildpacks/python buildpack
3. As expected, it'll build and the pip-install layer will be present in the launch image. This is the typical Python build, python-start requires `site-packages` with metadata `launch=true` to have it included.

Now:
1. Take the pip sample app
2. Use the following buildpack order: `-b paketo-buildpacks/python -b mock`. mock adds a `site-packages` + metadata `build=true` requirement. This simulates a buildpack that would run some python command during build.
3. The expected result is a.) mock works because python & pip dependencies are available at build b.) the same image is produced with python and the pip dependencies.

It is as if setting build=true overrides python-start which sets launch=true. 

Notes:
1. If the mock buildpack sets build=true & launch=true then it works. That's not always safe to do though.
2. If I log the buildplan that pip-install sees, it ultimately sets the launch/build flags based on this info, it only shows build=true.
3. If I substitute a mock buildpack for pip-install and cat out the build plan toml, I get this:

```toml
[[entries]]
  name = "site-packages"
  [entries.metadata]
    launch = "true"

[[entries]]
  name = "site-packages"
  [entries.metadata]
    build = "true"
```

That's the expected behavior as far as I'm aware. If multiple buildpacks require the same entry, you should see multiple entries listed (assuming that something hasn't consumed those entries already). It's as if packit is not seeing the full list. That said, looking through the code I can't spot where it would be doing that.

At any rate, I'm not 100% certain there's an issue here, but after reviewing all the basics with the buildplans & detect scripts nothing jumps out as a problem, and it's weird that packit doesn't seem to see both buildplan entries.

[mock.zip](https://github.com/paketo-buildpacks/packit/files/9782589/mock.zip)

**Comment by ryanmoran** [comment]
Can you provide some more details about how you are achieving Notes#3? I created my own mock buildpack and still only see a single entry.

**Comment by dmikusa** [comment]
I think this was a buildplan issue in one of the paketo-buildpacks (python-start). It just manifested in a weird way (mostly because of how little information pack/lifecycle gives you about the selected buildplan). Anyway, apologizes for the noise. Closing.
