### ISSUE TITLE
jam `summarize` should work with a docker registry link.

### ISSUE THREAD

**Issue by joshzarrabi** [paketo-buildpacks/packit#42]
Now that we are moving to buildpackages that are mostly stored on gcr, I believe `jam summarize` will be more useful if you do not have to download a tarball of the buildpackage, but can instead simply point to the gcr.io link. 

We will need to implement this logic somewhere in order to resolve this [issue](https://github.com/paketo-buildpacks/github-config/issues/101), and I am proposing it would be better to encode it into `jam` rather than a github action.

**Comment by ryanmoran** [comment]
I think this will ultimately get built into `pack`. There is already an open issue with a proposal here: https://github.com/buildpacks/pack/issues/642.

**Comment by ryanmoran** [comment]
Given that this is covered by `pack inspect-buildpack` now, I'd like to close this out.
