### ISSUE TITLE
FindDependencyMapping can not find any dependency mapping if only new checksum attribute is used

### ISSUE THREAD

**Issue by MischaFrank** [paketo-buildpacks/packit#420]
The Dependency attribute `SHA256` is deprecated and `checksum` should be used instead.

The `Deliver` method checks for an existing dependency mapping only with the `SHA256` attribute. If it is not present, because only the new `checksum` is used, no dependency mapping can be found.

Possible solution:
Use the SHA256 from the `checksum` to find dependency mappings. For backward compatibility use `SHA256` attribute if `checksum` is not present.

```
func (s Service) Deliver(dependency Dependency, cnbPath, layerPath, platformPath string) error {
	dependencyMappingURI, err := s.mappingResolver.FindDependencyMapping(dependency.SHA256, platformPath)
	if err != nil {
		return fmt.Errorf("failure checking for dependency mappings: %s", err)
	}

	if dependencyMappingURI != "" {
		dependency.URI = dependencyMappingURI
	}
```

Is my observation correct or am I missing something?

**Comment by sophiewigmore** [comment]
Hey @MischaFrank your observation is correct. We only just moved over to the `checksum` field and it seems like we missed a few places where `SHA256` is used in the library. `FindDependencyMapping` (and any related functions) should be modified to leverage `checksum` in a backwards-compatible way

**Comment by MischaFrank** [comment]
Thanks a lot for the fast fix!
