### ISSUE TITLE
Buildpack API 0.9: Remove Shell-Specific Logic

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/packit#431]
## Describe the Enhancement

Implement this [CNB RFC](https://github.com/buildpacks/rfcs/blob/main/text/0093-remove-shell-processes.md) to remove support for shell-specific logic when a buildpack uses API 0.9.

The primary change here is that the structure of the `processes` section in the `launch.toml` has changed.

## Motivation

Having support for the latest API versions is important to support not only our own project usecases, but those of our users as well.

**Comment by modulo11** [comment]
I naively started working on this in https://github.com/sap-contributions/packit/commit/ccfdf7e9e02c920a5bf3930b13fcd2d4647069ed but wondered how your typically deal with breaking changes in structs like `Process`. Would that be "parked" until `v3` is cut or should there be some `OldProcess` struct to stay compatible with older buildpack API versions?

**Comment by ryanmoran** [comment]
We try to maintain backwards-compatibility for as long as possible. So, if at all possible, we'd like to see a solution to this that doesn't break the API. If there really is not way around it, we can discuss alternatives.
