### ISSUE TITLE
jam `summarize` should have a JSON formatter

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/packit#45]
**Context**
We add the option to get a JSON payload from the `jam summarize` command through the `--format` flag to allow for the contents of a buildpackage to be consumed programmatically

**Acceptance Criteria**
When I run `jam summarize --buildpack buildpackage.cnb --format json`
Then I should receive a json payload of all of the buildpackage information

**Comment by ryanmoran** [comment]
### Proposed format examples:

#### Implementation: direct translation of buildpack.toml to JSON
```json
{
  "api": "0.2",
  "buildpack": {
    "id": "some-buildpack-id",
    "version": "1.2.3"
  },
  ...
}
```

#### Language families:
```json
{
  "api": "0.2",
  "buildpack": {
    "id": "some-buildpack-id",
    "version": "1.2.3"
  },
  "order": [
    {
      "grouping": {
        "id": "other-buildpack-id",
        "version": "2.3.4"
      }
    },
    ...
  ],
  "buildpacks": [
    <output for Implementation shown above>
  ]
  ...
}
```
