### ISSUE TITLE
SBoM helper code out-of-sync with upstream

### ISSUE THREAD

**Issue by thitch97** [paketo-buildpacks/packit#505]
## Expected Behavior

Fetching go modules before a unit test should succeed.

## Current Behavior

Unit Tests [fail](https://github.com/paketo-buildpacks/node-engine/actions/runs/5202083483/jobs/9383173135?pr=670) when getting go modules. 

## Possible Solution

From the error messages linked above, it seems that packit's implementation of the SBoM generation logic is no longer compatible with its counterpart upstream. The problem seems to originate from [this refactor](https://github.com/anchore/syft/pull/1743).

## Steps to Reproduce

1. Clone `paketo-buildpacks/node-engine` repository.
2. Run `go get -u all`
3. Run `./scripts/unit.sh`

**Comment by sophiewigmore** [comment]
We have decided not to do this for now because its a big undertaking that no one is necessarily asking for - and we will have to do it again as soon as another release comes out. Instead, we should find a different workaround for resolving the Go updates in buildpacks
