### ISSUE TITLE
Need a release 

### ISSUE THREAD

**Issue by mhdawson** [paketo-buildpacks/packit#611]
## Expected Behavior

We need a release so that I can get https://github.com/paketo-buildpacks/packit/pull/604 into Jam for our multi-arch support work related to the Node.js buildpacks

## Steps to Reproduce

1.

**Comment by mhdawson** [comment]
@ForestEckhardt any chance you could publish a release?

**Comment by ForestEckhardt** [comment]
https://github.com/paketo-buildpacks/packit/releases/tag/v2.16.0
