### ISSUE TITLE
Bug: Mixins are not being parsed

### ISSUE THREAD

**Issue by ameyer-pivotal** [paketo-buildpacks/packit#80]
It looks as though `jam` doesn't include any mixins when packaging buildpacks. This has led to false-positive test results (when we'd expect failures for mixins not provided by a given stack) and could ultimately mean we're shipping buildpacks that are packaged incorrectly.

See: https://github.com/paketo-buildpacks/packit/blob/859d48c13bd138df44158d765b1f9e57862a2454/cargo/config.go#L19

**Comment by ameyer-pivotal** [comment]
I think this points to a larger issue: these tools really should not be altering the repo's original `buildpack.toml`. Would y'all consider ways to avoid this in future versions of the tooling?

**Comment by ryanmoran** [comment]
I'd be open to hearing how you propose we could make that kind of change and support the set of features we already have, several of which (offline support, stack filtering, versioning) rely on the fact that the `buildpack.toml` is modified at build time.
