### ISSUE TITLE
Add usage flags to jam commands/subcommands

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/packit#94]
## What happened?

When I run any `jam` command/subcommand without the expected flags I see output similar to the following:
```
jam
missing command%
...
jam pack
failed to execute: missing required flag --buildpack
```

It would be helpful if usage commands/flags are added to all jam commands/subcommands (e.g `jam --help`, `jam help`, `jam pack --help`, etc..)

**Comment by emmjohnson** [comment]
I'll pick this up, cannot assign as I am not a contributor
